### ISSUE TITLE
CoreDNS Projects for CommunityBridge Program Q2 2020

### ISSUE THREAD

**Issue by yongtang** [coredns/rfc#7]
Please Note: This is a tracking issue for CommunityBridge Program Q2 2020. Anyone interested in this implementation should check link there in https://github.com/cncf/mentoring/tree/master/communitybridge/2020/q2

Please Note: This is reserved for CommunityBridge Program Q2 2020, we don't accept PRs outside of CommunityBridge Program Q2 2020, or without coordination with maintainers.

CNCF is participating CommunityBridge Program by Linux Foundation in Q2 2020. See [link](
https://github.com/cncf/mentoring/tree/master/communitybridge/2020/q2) for more details. As part of CNCF projects, CoreDNS is actively participating in CommunityBridge Program.

Below are the list of candidate CommunityBridge Program Q2 2020:

**External health check and orchestration of CoreDNS in Kubernetes clusters**

- Description: CoreDNS is the cluster DNS server for Kubernetes and is very much critical for the overall health of the Kubernetes cluster. It is very important to monitoring the health of CoreDNS itself and restarting or repairing any CoreDNS pods that are not behaving correctly. While CoreDNS exposes a health check itself, the health check is not UDP (DNS) based. The existing health check is also launched locally which could be very much different when accessed by other pods remotely.
  This project intends to build an application that checks CoreDNS health through UDP (DNS) externally, and, restart CoreDNS pods by interacting with Kubernetes API through golang. This is an important project that will greatly improve the overall health of Kubernetes clusters through automation.
- Recommended Skills:  Go, DNS, Kubernetes
- Mentor(s): Yong Tang (@yongtang), Paul Greenberg (@greenpau)
- Implementation: The deliverable of this project is a golang program that could be deployed in a Kubernetes cluster independently while at the same time, monitoring CoreDNS pods in the same cluster and interacting Kubernetes API (server) to restart CoreDNS pods as needed.
- Reference: Please see coredns/coredns#3617 for some related discussions.

**Comment by darshanime** [comment]
Hi @yongtang,
If I understand correctly, this project only addresses CoreDNS deployed in Kubernetes, and the health checker (the deliverable of this project) can be deployed in Kubernetes/externally?

Also, to apply, should one create a analysis doc and share in the application on CB website directly, or create a PR in this repo with the analysis? I see some PRs with the latter approach, but that is for GSoC, not for CB. 

Thanks!

**Comment by wjayesh** [comment]
Hello! I have applied to become a mentee at the Community Bridge website and have been assigned a task to submit a cover letter that should answer questions about the motivation behind my application and such. 
Where should I submit my proposal for this idea?

**Comment by yongtang** [comment]
@darshanime @WJayesh For any proposals, please submit a PR in this repo, as was described in the README.md. We will merge the proposal if it is accepted with confirmation from CNCF.

**Comment by yongtang** [comment]
You can email the cover letter and statement to me and Paul.

**Comment by yongtang** [comment]
The updated timeline for this project:
https://github.com/cncf/mentoring/pull/227/files

We will make a recommendation during the weekend.

**Comment by Dhiraj240** [comment]
@yongtang I will be applying to community bridge for this project. Soon I will share my draft PR, should I share pseudo-codes in that or just the theory?
Just to confirm the resumes and CV should be shared on the emails which are flashed on your GitHub profile?

**Comment by yongtang** [comment]
@Dhiraj240  Proposal submissions will need to open a PR in this repo, as was specified in the `README.md`. In addition, if there are any other requests from CommunityBridge program please check with https://github.com/cncf/mentoring/tree/master/communitybridge/2020/q2, or forward additional materials to my email (see GitHub profile).

**Comment by yongtang** [comment]
The project has been completed, and is available in now:

https://github.com/wjayesh/coredns-healthcheck
